### ISSUE TITLE
Linux Mint Issue

### ISSUE THREAD

**Issue by ech0pandit** [Dragon2fly/vpngate-with-proxy#29]
(vpn_indicator.py:17228): Gdk-CRITICAL **: 13:28:51.754: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Traceback (most recent call last):
  File "vpnproxy_tui.py", line 1090, in <module>
    screen = Display(vpn_connect)
  File "vpnproxy_tui.py", line 605, in __init__
    self.table = self.make_GUI()  # list of lines, urwid.columns
  File "vpnproxy_tui.py", line 801, in make_GUI
    self.Udata.append(deepcopy(Ulabel))
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 352, in _reconstruct
    y.append(item)
  File "/usr/local/lib/python2.7/dist-packages/urwid/monitored_list.py", line 384, in append
    rval = super(MonitoredFocusList, self).append(item)
  File "/usr/local/lib/python2.7/dist-packages/urwid/monitored_list.py", line 30, in call_modified_wrapper
    self._modified()
  File "/usr/local/lib/python2.7/dist-packages/urwid/container.py", line 1816, in _contents_modified
    self._selectable = any(w.selectable() for w, o in self.contents)
  File "/usr/local/lib/python2.7/dist-packages/urwid/container.py", line 1906, in _get_contents
    return self._contents
AttributeError: 'Columns' object has no attribute '_contents'

**Comment by luoxufeiyan** [comment]
I got the same issue. However, the CLI mode works fine.

FYI, I'm using Linux Mint 19.3 and the `python-urwid` version is 2.0.1-2.

**Comment by Dragon2fly** [comment]
Thank you, @luoxufeiyan 
I fixed that error, now it works with latest `python-urwid` too.
Also since python2 is deprecated, `vpngate-with-proxy` now works with python3.6+
